---

name: th-base-functors
version: 0.1.0.0

author: Daniel Trowbridge
copyright: 2023 Daniel Trowbridge
github: danieljtrowbridge/th-base-functors
license: MIT
maintainer: danieljtrowbridge@pm.me

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs:
    - src

tests:
  spec:
    dependencies:
      - th-base-functors
    main: Main.hs
    source-dirs:
      - test
