---

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    permissions:
      id-token: write
      pages: write
    uses: danieljtrowbridge/hs-config/.github/workflows/ci_docs.yaml@main
    with:
      ghc-version: 9.4.7
      package: th-base-functors
  yamllint:
    name: Run yamllint
    uses: danieljtrowbridge/hs-config/.github/workflows/yamllint.yaml@main
