---

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    uses: danieljtrowbridge/hs-config/.github/workflows/ci.yaml@main
    with:
      ghc-version: 9.4.7
      package: th-base-functors
